name: 'Cancel Workflow Runs By Status'
description: 'This Action will cancel any previous runs that are not `completed` for a given workflow.'
author: jmoll-hn
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  workflow_id:
    description: 'Optional - A single Workflow ID or a comma separated list of IDs'
    required: false
  ignore_sha:
    description: 'Optional - Allow canceling other workflows with the same SHA. Useful for the `pull_request.closed` event.'
    required: false
    default: 'false'
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
    required: true
  all_but_latest:
    description: "Cancel all actions but the last one"
    required: false
    default: 'false'
  status:
    description: "For example `queued,in_progress,completed`, defaults to all except `completed`"
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
